/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/market-signals/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /market-signals/series — 市场信号时间序列 feed (apiserver 对外)。 */
        get: operations["get_market_signal_series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threat-intel/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /threat-intel/feed — 威胁情报 feed (apiserver 对外, 直读 ClickHouse typed 表)。 */
        get: operations["get_threat_feed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/auth/handshake/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_app_handshake"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v2_app_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v2_app_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_app_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/community/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_app_list_accounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/community/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_app_get_account"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/community/accounts/{account_id}/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_app_account_publications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/community/presence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_app_get_presence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/community/presence/beat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v2_app_presence_beat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["v2_app_update_profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/me/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_app_my_publications"];
        put?: never;
        post: operations["v2_app_create_publication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/me/publications/{publication_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["v2_app_delete_publication"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/sync/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_app_sync_limits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/sync/{sync_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_app_get_sync"];
        put: operations["v2_app_put_sync"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/sync/{sync_id}/generations/{generation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["v2_app_discard_sync_generation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/sync/{sync_id}/generations/{generation}/parts/{part_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_app_get_sync_generation_part"];
        put: operations["v2_app_put_sync_generation_part"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/app/sync/{sync_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_app_get_sync_manifest"];
        put: operations["v2_app_commit_sync_manifest"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/analytics/corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v2/data/analytics/corpus — 语料真实聚合: 总量 + 近 N 小时按小时入库量
         *     (与 `/v1/stats/corpus` 同口径, 供 admin 仪表盘)。需 `analytics:read` scope。
         */
        get: operations["corpus_analytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/analytics/entities/trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["trending_entities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/analytics/events/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["query_events"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/analytics/events/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["top_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/catalog/publishers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_data_list_publishers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/catalog/publishers/{publisher_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_data_get_publisher"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/corpus/articles/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["query_articles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/corpus/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v2_data_get_article"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/datasets/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["papers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/datasets/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/graph/articles/{article_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["related_articles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/graph/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_entities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/graph/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_entity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/graph/entities/{entity_id}/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["entity_neighbors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/intel/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["indicators"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/data/signals/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["market_signals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/extensions/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v2/extensions/registry — ideall 官方签名扩展目录页。
         * @description 路径由 `/v1/extensions/registry` 迁移而来 (随 v1 整体退役); ideall 客户端需同步更新
         *     拉取地址。挂载方式不变: 经 `public_integration_router()` 直接 merge 到根路由, 与业务
         *     API 版本切换无关, 始终可用。
         */
        get: operations["get_extension_registry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/public/geo/ip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v2/public/geo/ip[?ip=] — 定位访问者所在城市, 公开端点 (无需 service token)。
         *     定位口径: 信任门控 + CF 头 + 转发头 + 查库 (`infra::geoip`); 定位失败时经纬度 0。
         *     挂载于 `data_token_boundary` 之外 (见 `v2::router`), 供 portal/ideall 匿名地图视图直连。
         */
        get: operations["get_ip_location"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AltDataObservation: {
            /**
             * Format: int64
             * @description Wonita 入库/得知该观测的时刻 (epoch 毫秒, UTC), 可用于后续无未来函数投影。
             */
            collect_time_ms: number;
            /** @description 地理维, 如 WLD/CHN; 无地理维时为空串。 */
            geo: string;
            /** @description 被描述周期, 如 2022。不是 point-in-time 可知时刻。 */
            obs_date: string;
            /** @description 指标/序列标识, 如 SP.POP.TOTL。 */
            series_id: string;
            /** @description 结构化源标识, 如 worldbank-pop。 */
            source: string;
            unit: string;
            /** Format: double */
            value: number;
        };
        AuthBody: {
            token: string;
            token_type: string;
        };
        /**
         * @description 注册 / 登录请求体。密码经客户端公钥与服务端临时密钥协商出的共享密钥
         *     AEAD 加密后, 以 hex 字符串传输。
         */
        AuthPayload: {
            /** @description 用户(浏览器)指纹, 用作 SessionID */
            client_id: string;
            /** @description 客户端 X25519 公钥 (hex) */
            client_secret: string;
            email: string;
            /** @description 加密后的密码 (hex): 前 24 字节为 nonce, 末 16 字节为 Poly1305 标签, 中间为密文 */
            encrypted_password: string;
        };
        /** @description 一个城市的在线聚合 (访客匿名计数 + 成员去重计数)。 */
        CityPresence: {
            city: string;
            country: string;
            /**
             * Format: int32
             * @description 未登录访客数 (按 sid 计, 匿名)
             */
            guests: number;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            /**
             * Format: int32
             * @description 登录成员数 (按 account_id 去重)
             */
            members: number;
        };
        /**
         * @description 语料总量 + 近 N 小时按小时入库量分桶。
         *     total_articles 为 ClickHouse info FINAL 去重后的当前总量 (含全部历史)。
         */
        CorpusStats: {
            buckets: components["schemas"]["CorpusStatsBucket"][];
            /** Format: int64 */
            total_articles: number;
            /** Format: int32 */
            window_hours: number;
        };
        /** @description 语料统计的单桶入库量 (按小时)。 */
        CorpusStatsBucket: {
            /**
             * Format: int64
             * @description 桶起点 (epoch 毫秒, UTC 整点)
             */
            bucket_start_ms: number;
            /**
             * Format: int64
             * @description 该桶入库文章数
             */
            count: number;
        };
        ErrorDetail: {
            code: string;
            message: string;
        };
        /** @description 所有 HTTP 错误（含 JWT 401/429）的统一机器可读包络。 */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        ExtensionRegistryEnvelope: {
            /** @description 由官方 Minisign 根签名的精确 JSON UTF-8 字符串。 */
            payload: string;
            /** Format: int32 */
            schemaVersion: number;
            /** @description Tauri/minisign 的 Base64 签名文件文本。 */
            signature: string;
        };
        /** @description 握手响应: 服务端临时 X25519 公钥 (hex)。 */
        Handshake: {
            /** @description 服务端临时公钥 (hex 明文串), 供客户端 AEAD 加密密码。 */
            public_key: string;
        };
        /**
         * @description 访问者 IP 地理定位结果 (供社区地图默认聚焦访问者所在城市)。
         *     经纬度由服务端对访问者 IP 做地理定位得到; 定位失败时经纬度为 0。
         */
        IpLocation: {
            city: string;
            country: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        MarketSignalPoint: {
            /** @description 市场信号标识。 */
            key: string;
            /**
             * Format: int64
             * @description 信号可知时刻 (epoch 毫秒, UTC)。
             */
            ts: number;
            /**
             * Format: double
             * @description 信号值。
             */
            value: number;
        };
        SciTechPaper: {
            abstract: string;
            authors: string[];
            /** @description 分类标签, 如 cs.CR / cs.AI。 */
            categories: string[];
            doi: string;
            /** @description 源内主键, 如 arXiv id 2401.12345。 */
            paper_id: string;
            /** @description PDF 地址。 */
            pdf_url: string;
            published?: string | null;
            /** @description 结构化源标识, 如 arxiv-cs-cr。 */
            source: string;
            title: string;
            updated?: string | null;
            /** @description 论文摘要页。 */
            url: string;
        };
        /** @description v2 online member identity uses the stable PostgreSQL account ID. */
        StableOnlineMember: {
            account_id: string;
            city: string;
            country: string;
            display_name: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        StablePresenceSnapshot: {
            cities: components["schemas"]["CityPresence"][];
            members: components["schemas"]["StableOnlineMember"][];
            /** Format: int32 */
            total_guests: number;
            /** Format: int32 */
            total_members: number;
        };
        ThreatFeedResponse: {
            indicators: components["schemas"]["ThreatIndicator"][];
            /**
             * Format: int64
             * @description 增量同步水印: 本次返回的最大 collect_time (epoch 毫秒), 供下次作 since 续拉。
             */
            max_collect_time_ms?: number | null;
            source: string;
        };
        ThreatIndicator: {
            category: string;
            /** Format: int32 */
            confidence?: number | null;
            description?: string | null;
            first_seen?: string | null;
            last_seen?: string | null;
            reference?: string | null;
            severity: string;
            source?: string | null;
            tags?: string[] | null;
            type: string;
            value: string;
        };
        UserClaimsData: {
            /** @description v1 已发布的 session 字段；当前无头像写入源时保持 null。 */
            avatar?: string | null;
            email: string;
            /** Format: int64 */
            id: number;
            name: string;
        };
        V2AppClaimsData: {
            account_id: string;
            display_name: string;
            email: string;
        };
        V2AppNewPublication: {
            body?: string;
            title: string;
            url?: string;
        };
        V2AppPresenceBeat: {
            sid: string;
        };
        V2AppProfileUpdate: {
            display_name: string;
        };
        V2AppPublicAccount: {
            account_id: string;
            /** Format: int64 */
            created_at_ms: number;
            display_name: string;
            /** Format: int64 */
            publication_count: number;
        };
        V2AppPublication: {
            body: string;
            /** Format: int64 */
            created_at_ms: number;
            owner_account_id: string;
            publication_id: string;
            title: string;
            /** Format: int64 */
            updated_at_ms: number;
            url: string;
        };
        V2AppSyncBlob: {
            ciphertext: string;
            iv: string;
            /** Format: int64 */
            updated_at_ms: number;
            /** Format: int64 */
            version: number;
        };
        V2AppSyncGenerationPart: {
            ciphertext: string;
            content_sha256: string;
            generation: string;
            iv: string;
            /** Format: int32 */
            part_index: number;
        };
        V2AppSyncManifest: {
            generation: string;
            /** Format: int32 */
            part_count: number;
            /** @description SHA-256 over the ordered `part_index:content_sha256\n` entries. */
            parts_sha256: string;
            /** Format: int64 */
            total_ciphertext_chars: number;
            /** Format: int64 */
            updated_at_ms: number;
            /**
             * Format: int64
             * @description Opaque, server-maintained CAS version. The first committed manifest is version 1.
             */
            version: number;
        };
        V2AppSyncManifestWrite: {
            /** @description Fresh lowercase 128-bit hex generation identifier. */
            generation: string;
            /**
             * Format: int32
             * @description Exact number of parts; committed indices must be contiguous `0..part_count`.
             */
            part_count: number;
        };
        V2AppSyncPartReceipt: {
            /** Format: int32 */
            ciphertext_chars: number;
            /** @description SHA-256 of `iv + NUL + ciphertext`, lowercase hex. */
            content_sha256: string;
            created: boolean;
            generation: string;
            /** Format: int32 */
            part_index: number;
        };
        V2AppSyncPartWrite: {
            /** @description Canonical standard Base64 ciphertext including the AES-GCM tag. */
            ciphertext: string;
            /** @description Canonical standard Base64 for a 12-byte AES-GCM IV. */
            iv: string;
        };
        V2AppSyncProtocolLimits: {
            /** Format: int64 */
            max_account_ciphertext_chars: number;
            /** Format: int64 */
            max_generation_ciphertext_chars: number;
            /** Format: int32 */
            max_part_ciphertext_chars: number;
            /** Format: int32 */
            max_parts_per_generation: number;
            /**
             * Format: int32
             * @description Dedicated authenticated per-IP budget for all partitioned sync routes.
             */
            max_requests_per_minute: number;
            /** Format: int32 */
            max_staged_generations_per_sync: number;
            /** Format: int32 */
            max_sync_ids_per_account: number;
            /**
             * Format: int64
             * @description Idle TTL for uncommitted generations. Later sync writes lazily collect expired entries.
             */
            staged_generation_idle_ttl_ms: number;
        };
        V2AppSyncWrite: {
            ciphertext: string;
            iv: string;
        };
        V2DataArticle: {
            article_id: string;
            body: string;
            canonical_url: string;
            /** Format: int64 */
            collected_at_ms: number;
            enclosures?: unknown[];
            entities?: components["schemas"]["V2DataEntityMention"][];
            geo_scope: string[];
            language: string;
            platform_type: string;
            /** Format: int64 */
            published_at_ms: number;
            publisher_country: string;
            publisher_domain: string;
            publisher_id: string;
            revision_id: string;
            source_category: string;
            source_id: string;
            title: string;
            topics: string[];
            /** Format: int64 */
            version_ms: number;
        };
        V2DataArticleQuery: {
            cursor?: string | null;
            entity_ids?: string[] | null;
            /** Format: int64 */
            from_ms?: number | null;
            geo_scope?: string[] | null;
            language?: string | null;
            /** Format: int32 */
            limit?: number | null;
            platform_type?: string | null;
            publisher_country_prefix?: string | null;
            publisher_id?: string | null;
            q?: string | null;
            source_category?: string | null;
            /** Format: int64 */
            to_ms?: number | null;
            topics?: string[] | null;
        };
        V2DataEntity: {
            canonical_name: string;
            description?: string | null;
            display_name: string;
            entity_id: string;
            has_entry: boolean;
            label: string;
            qid?: string | null;
            /** Format: int64 */
            updated_at_ms: number;
            wikipedia_url?: string | null;
        };
        V2DataEntityDetail: components["schemas"]["V2DataEntity"] & {
            /** Format: int64 */
            first_seen_ms: number;
            /** Format: int64 */
            last_seen_ms: number;
            /** Format: int64 */
            mention_count: number;
            weekly: components["schemas"]["V2DataEntityPeriodCount"][];
        };
        V2DataEntityMention: {
            canonical_name: string;
            /** Format: double */
            confidence: number;
            entity_id: string;
            label: string;
            qid: string;
            surface: string;
        };
        V2DataEntityNeighbor: {
            entity: components["schemas"]["V2DataEntity"];
            /** Format: double */
            score: number;
            /** Format: int64 */
            shared_articles: number;
        };
        V2DataEntityPeriodCount: {
            /** Format: int64 */
            mention_count: number;
            /** Format: int64 */
            period_ms: number;
        };
        V2DataEventQuery: {
            cursor?: string | null;
            /** Format: int64 */
            from_ms?: number | null;
            geo_scope?: string[] | null;
            language?: string | null;
            /** Format: int32 */
            limit?: number | null;
            publisher_country_prefix?: string | null;
            source_category?: string | null;
            /** Format: int64 */
            to_ms?: number | null;
            topics?: string[] | null;
            window?: string | null;
        };
        V2DataEventResult: {
            display_title: string;
            event_id: string;
            lead: components["schemas"]["V2DataArticle"];
            related: components["schemas"]["V2DataArticle"][];
            /** Format: int32 */
            source_count: number;
        };
        V2DataMarketSignalPoint: {
            key: string;
            /** Format: int64 */
            ts_ms: number;
            /** Format: double */
            value: number;
        };
        V2DataPaper: {
            abstract: string;
            authors: string[];
            categories: string[];
            doi: string;
            paper_id: string;
            pdf_url: string;
            /** Format: int64 */
            published_at_ms?: number | null;
            source: string;
            title: string;
            /** Format: int64 */
            updated_at_ms?: number | null;
            url: string;
        };
        V2DataPublisher: {
            /** Format: int64 */
            article_count: number;
            category: string;
            city: string;
            country: string;
            domain: string;
            /** Format: int64 */
            latest_published_at_ms: number;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
            name: string;
            publisher_id: string;
        };
        V2DataRelatedArticle: {
            article: components["schemas"]["V2DataArticle"];
            /** Format: double */
            score: number;
            /** Format: int64 */
            shared_entities: number;
        };
        V2DataSeriesObservation: {
            /** Format: int64 */
            collect_time_ms: number;
            geo: string;
            observation_period: string;
            series_id: string;
            source: string;
            unit: string;
            /** Format: double */
            value: number;
        };
        V2DataThreatIndicator: {
            category: string;
            /** Format: int32 */
            confidence?: number | null;
            description?: string | null;
            /** Format: int64 */
            first_seen_ms?: number | null;
            /** Format: int64 */
            last_seen_ms?: number | null;
            reference?: string | null;
            severity: string;
            source?: string | null;
            tags?: string[] | null;
            type: string;
            value: string;
        };
        V2DataTrendingEntity: {
            canonical_name: string;
            entity_id: string;
            label: string;
            /** Format: int64 */
            mention_count: number;
        };
        V2Meta: {
            /** Format: int64 */
            generated_at_ms: number;
            has_more: boolean;
            next_cursor?: string | null;
            projection_watermark?: null | components["schemas"]["V2ProjectionWatermark"];
        };
        V2ProjectionWatermark: {
            /** Format: int64 */
            corpus_version_ms: number;
            /** Format: int64 */
            graph_version_ms: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_market_signal_series: {
        parameters: {
            query: {
                /** @description 市场信号标识, 如 mention_count.BTC。 */
                key: string;
                /** @description 起始时间 (epoch 毫秒, UTC, 含)。 */
                from: number;
                /** @description 结束时间 (epoch 毫秒, UTC, 含)。 */
                to: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description point-in-time 市场信号序列 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketSignalPoint"][];
                };
            };
            /** @description 非法时间范围 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_threat_feed: {
        parameters: {
            query?: {
                /** @description kcatta=仅 ip/domain/ja3; turn=全类型含 cve。 */
                format?: string;
                /** @description 仅返回置信 >= 此值的指标。 */
                min_confidence?: number;
                /**
                 * @description 增量同步水印: 仅返回 collect_time >= 此值 (epoch 毫秒) 的指标 (TAXII added_after 同型);
                 *     响应 max_collect_time_ms 供下次续拉。缺省为全量 (历史行为)。
                 */
                since_ms?: number;
                /** @description 返回条数上限 (默认全量; 增量模式建议 500)。 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 威胁情报 FeedFile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreatFeedResponse"];
                };
            };
            /** @description 非法 format/min_confidence */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ClickHouse 数据查询失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v2_app_handshake: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ephemeral server public key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 握手响应: 服务端临时 X25519 公钥 (hex)。 */
                        data: {
                            /** @description 服务端临时公钥 (hex 明文串), 供客户端 AEAD 加密密码。 */
                            public_key: string;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    v2_app_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthPayload"];
            };
        };
        responses: {
            /** @description authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            token: string;
                            token_type: string;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description authentication capacity exhausted */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v2_app_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthPayload"];
            };
        };
        responses: {
            /** @description registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            token: string;
                            token_type: string;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description email exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description authentication capacity exhausted */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v2_app_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current app session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            account_id: string;
                            display_name: string;
                            email: string;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description invalid JWT admission is exhausted */
            429: {
                headers: {
                    /** @description seconds before retry */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    v2_app_list_accounts: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description public account catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            account_id: string;
                            /** Format: int64 */
                            created_at_ms: number;
                            display_name: string;
                            /** Format: int64 */
                            publication_count: number;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    v2_app_get_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description public account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            account_id: string;
                            /** Format: int64 */
                            created_at_ms: number;
                            display_name: string;
                            /** Format: int64 */
                            publication_count: number;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v2_app_account_publications: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description account publications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            body: string;
                            /** Format: int64 */
                            created_at_ms: number;
                            owner_account_id: string;
                            publication_id: string;
                            title: string;
                            /** Format: int64 */
                            updated_at_ms: number;
                            url: string;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    v2_app_get_presence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description stable-account presence snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            cities: components["schemas"]["CityPresence"][];
                            members: components["schemas"]["StableOnlineMember"][];
                            /** Format: int32 */
                            total_guests: number;
                            /** Format: int32 */
                            total_members: number;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    v2_app_presence_beat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2AppPresenceBeat"];
            };
        };
        responses: {
            /** @description presence snapshot after heartbeat */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            cities: components["schemas"]["CityPresence"][];
                            members: components["schemas"]["StableOnlineMember"][];
                            /** Format: int32 */
                            total_guests: number;
                            /** Format: int32 */
                            total_members: number;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description explicit JWT is invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description invalid JWT admission is exhausted */
            429: {
                headers: {
                    /** @description seconds before retry */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    v2_app_update_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2AppProfileUpdate"];
            };
        };
        responses: {
            /** @description profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            account_id: string;
                            display_name: string;
                            email: string;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description invalid JWT admission is exhausted */
            429: {
                headers: {
                    /** @description seconds before retry */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    v2_app_my_publications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current account publications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            body: string;
                            /** Format: int64 */
                            created_at_ms: number;
                            owner_account_id: string;
                            publication_id: string;
                            title: string;
                            /** Format: int64 */
                            updated_at_ms: number;
                            url: string;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description invalid JWT admission is exhausted */
            429: {
                headers: {
                    /** @description seconds before retry */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    v2_app_create_publication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2AppNewPublication"];
            };
        };
        responses: {
            /** @description publication created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            body: string;
                            /** Format: int64 */
                            created_at_ms: number;
                            owner_account_id: string;
                            publication_id: string;
                            title: string;
                            /** Format: int64 */
                            updated_at_ms: number;
                            url: string;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description invalid JWT admission is exhausted */
            429: {
                headers: {
                    /** @description seconds before retry */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    v2_app_delete_publication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description publication deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description invalid JWT admission is exhausted */
            429: {
                headers: {
                    /** @description seconds before retry */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    v2_app_sync_limits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description partitioned sync protocol limits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** Format: int64 */
                            max_account_ciphertext_chars: number;
                            /** Format: int64 */
                            max_generation_ciphertext_chars: number;
                            /** Format: int32 */
                            max_part_ciphertext_chars: number;
                            /** Format: int32 */
                            max_parts_per_generation: number;
                            /**
                             * Format: int32
                             * @description Dedicated authenticated per-IP budget for all partitioned sync routes.
                             */
                            max_requests_per_minute: number;
                            /** Format: int32 */
                            max_staged_generations_per_sync: number;
                            /** Format: int32 */
                            max_sync_ids_per_account: number;
                            /**
                             * Format: int64
                             * @description Idle TTL for uncommitted generations. Later sync writes lazily collect expired entries.
                             */
                            staged_generation_idle_ttl_ms: number;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    v2_app_get_sync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sync_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description encrypted sync blob */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            ciphertext: string;
                            iv: string;
                            /** Format: int64 */
                            updated_at_ms: number;
                            /** Format: int64 */
                            version: number;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description invalid JWT admission is exhausted */
            429: {
                headers: {
                    /** @description seconds before retry */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    v2_app_put_sync: {
        parameters: {
            query: {
                expected: number;
            };
            header?: never;
            path: {
                sync_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2AppSyncWrite"];
            };
        };
        responses: {
            /** @description encrypted sync blob updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            ciphertext: string;
                            iv: string;
                            /** Format: int64 */
                            updated_at_ms: number;
                            /** Format: int64 */
                            version: number;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description version conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description invalid JWT admission is exhausted */
            429: {
                headers: {
                    /** @description seconds before retry */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    v2_app_discard_sync_generation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sync_id: string;
                generation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description uncommitted generation discarded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description generation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description committed generation cannot be discarded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v2_app_get_sync_generation_part: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sync_id: string;
                generation: string;
                part_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description part from the currently committed generation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            ciphertext: string;
                            content_sha256: string;
                            generation: string;
                            iv: string;
                            /** Format: int32 */
                            part_index: number;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description generation is uncommitted, superseded, or part is absent */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v2_app_put_sync_generation_part: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sync_id: string;
                generation: string;
                part_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2AppSyncPartWrite"];
            };
        };
        responses: {
            /** @description immutable part stored or idempotently confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** Format: int32 */
                            ciphertext_chars: number;
                            /** @description SHA-256 of `iv + NUL + ciphertext`, lowercase hex. */
                            content_sha256: string;
                            created: boolean;
                            generation: string;
                            /** Format: int32 */
                            part_index: number;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description invalid id, index, IV, or ciphertext */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description part differs from an existing immutable part or generation is committed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description sync storage quota exceeded */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v2_app_get_sync_manifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sync_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description currently committed generation manifest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            generation: string;
                            /** Format: int32 */
                            part_count: number;
                            /** @description SHA-256 over the ordered `part_index:content_sha256\n` entries. */
                            parts_sha256: string;
                            /** Format: int64 */
                            total_ciphertext_chars: number;
                            /** Format: int64 */
                            updated_at_ms: number;
                            /**
                             * Format: int64
                             * @description Opaque, server-maintained CAS version. The first committed manifest is version 1.
                             */
                            version: number;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description no committed generation */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v2_app_commit_sync_manifest: {
        parameters: {
            query: {
                expected: number;
            };
            header?: never;
            path: {
                sync_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2AppSyncManifestWrite"];
            };
        };
        responses: {
            /** @description manifest atomically committed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            generation: string;
                            /** Format: int32 */
                            part_count: number;
                            /** @description SHA-256 over the ordered `part_index:content_sha256\n` entries. */
                            parts_sha256: string;
                            /** Format: int64 */
                            total_ciphertext_chars: number;
                            /** Format: int64 */
                            updated_at_ms: number;
                            /**
                             * Format: int64
                             * @description Opaque, server-maintained CAS version. The first committed manifest is version 1.
                             */
                            version: number;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description invalid manifest */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description manifest version conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description generation is incomplete or exceeds quota */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    corpus_analytics: {
        parameters: {
            query?: {
                /** @description 入库量分桶窗口 (小时, 默认 12, 上限 168) */
                window_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description corpus total + hourly ingest buckets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description 语料总量 + 近 N 小时按小时入库量分桶。
                         *     total_articles 为 ClickHouse info FINAL 去重后的当前总量 (含全部历史)。
                         */
                        data: {
                            buckets: components["schemas"]["CorpusStatsBucket"][];
                            /** Format: int64 */
                            total_articles: number;
                            /** Format: int32 */
                            window_hours: number;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description missing analytics scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trending_entities: {
        parameters: {
            query?: {
                window_hours?: number | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description trending entities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            canonical_name: string;
                            entity_id: string;
                            label: string;
                            /** Format: int64 */
                            mention_count: number;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description missing analytics scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    query_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2DataEventQuery"];
            };
        };
        responses: {
            /** @description event snapshots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            display_title: string;
                            event_id: string;
                            lead: components["schemas"]["V2DataArticle"];
                            related: components["schemas"]["V2DataArticle"][];
                            /** Format: int32 */
                            source_count: number;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    top_events: {
        parameters: {
            query?: {
                window?: string | null;
                limit?: number | null;
                cursor?: string | null;
                source_category?: string | null;
                language?: string | null;
                publisher_country_prefix?: string | null;
                topics?: string[] | null;
                geo_scope?: string[] | null;
                from_ms?: number | null;
                to_ms?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description top event snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            display_title: string;
                            event_id: string;
                            lead: components["schemas"]["V2DataArticle"];
                            related: components["schemas"]["V2DataArticle"][];
                            /** Format: int32 */
                            source_count: number;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    v2_data_list_publishers: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description publisher catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** Format: int64 */
                            article_count: number;
                            category: string;
                            city: string;
                            country: string;
                            domain: string;
                            /** Format: int64 */
                            latest_published_at_ms: number;
                            /** Format: double */
                            latitude?: number | null;
                            /** Format: double */
                            longitude?: number | null;
                            name: string;
                            publisher_id: string;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    v2_data_get_publisher: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publisher_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description publisher */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** Format: int64 */
                            article_count: number;
                            category: string;
                            city: string;
                            country: string;
                            domain: string;
                            /** Format: int64 */
                            latest_published_at_ms: number;
                            /** Format: double */
                            latitude?: number | null;
                            /** Format: double */
                            longitude?: number | null;
                            name: string;
                            publisher_id: string;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    query_articles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2DataArticleQuery"];
            };
        };
        responses: {
            /** @description cursor-paged article corpus */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            article_id: string;
                            body: string;
                            canonical_url: string;
                            /** Format: int64 */
                            collected_at_ms: number;
                            enclosures?: unknown[];
                            entities?: components["schemas"]["V2DataEntityMention"][];
                            geo_scope: string[];
                            language: string;
                            platform_type: string;
                            /** Format: int64 */
                            published_at_ms: number;
                            publisher_country: string;
                            publisher_domain: string;
                            publisher_id: string;
                            revision_id: string;
                            source_category: string;
                            source_id: string;
                            title: string;
                            topics: string[];
                            /** Format: int64 */
                            version_ms: number;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    v2_data_get_article: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current authoritative article revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            article_id: string;
                            body: string;
                            canonical_url: string;
                            /** Format: int64 */
                            collected_at_ms: number;
                            enclosures?: unknown[];
                            entities?: components["schemas"]["V2DataEntityMention"][];
                            geo_scope: string[];
                            language: string;
                            platform_type: string;
                            /** Format: int64 */
                            published_at_ms: number;
                            publisher_country: string;
                            publisher_domain: string;
                            publisher_id: string;
                            revision_id: string;
                            source_category: string;
                            source_id: string;
                            title: string;
                            topics: string[];
                            /** Format: int64 */
                            version_ms: number;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    papers: {
        parameters: {
            query?: {
                source?: string | null;
                category?: string | null;
                /** @description 标题大小写不敏感检索 (最多 200 字符)。 */
                q?: string | null;
                /** @description 发表时间窗 (ISO 字符串闭区间)。 */
                published_from?: string | null;
                published_to?: string | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description paper dataset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            abstract: string;
                            authors: string[];
                            categories: string[];
                            doi: string;
                            paper_id: string;
                            pdf_url: string;
                            /** Format: int64 */
                            published_at_ms?: number | null;
                            source: string;
                            title: string;
                            /** Format: int64 */
                            updated_at_ms?: number | null;
                            url: string;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    series: {
        parameters: {
            query?: {
                source?: string | null;
                series_id?: string | null;
                geo?: string | null;
                /** @description 观测时间窗 (obs_date 闭区间)。 */
                obs_from?: string | null;
                obs_to?: string | null;
                /** @description 可知时刻过滤: 仅 collect_time <= 此值 (epoch 毫秒) 的观测 (回测防未来函数)。 */
                asof_ms?: number | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description time-series dataset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** Format: int64 */
                            collect_time_ms: number;
                            geo: string;
                            observation_period: string;
                            series_id: string;
                            source: string;
                            unit: string;
                            /** Format: double */
                            value: number;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    related_articles: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description related articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            article: components["schemas"]["V2DataArticle"];
                            /** Format: double */
                            score: number;
                            /** Format: int64 */
                            shared_entities: number;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description graph unavailable or behind */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_entities: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description entity catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            canonical_name: string;
                            description?: string | null;
                            display_name: string;
                            entity_id: string;
                            has_entry: boolean;
                            label: string;
                            qid?: string | null;
                            /** Format: int64 */
                            updated_at_ms: number;
                            wikipedia_url?: string | null;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    get_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description entity identity and bounded corpus statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["V2DataEntity"] & {
                            /** Format: int64 */
                            first_seen_ms: number;
                            /** Format: int64 */
                            last_seen_ms: number;
                            /** Format: int64 */
                            mention_count: number;
                            weekly: components["schemas"]["V2DataEntityPeriodCount"][];
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    entity_neighbors: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description co-occurring entities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            entity: components["schemas"]["V2DataEntity"];
                            /** Format: double */
                            score: number;
                            /** Format: int64 */
                            shared_articles: number;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
            /** @description graph unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    indicators: {
        parameters: {
            query?: {
                format?: string | null;
                min_confidence?: number | null;
                limit?: number | null;
                cursor?: string | null;
                /** @description 增量水印: 仅返回 collect_time >= 此值 (epoch 毫秒) 的指标 (与 keyset 游标正交组合)。 */
                since_ms?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description threat indicators */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            category: string;
                            /** Format: int32 */
                            confidence?: number | null;
                            description?: string | null;
                            /** Format: int64 */
                            first_seen_ms?: number | null;
                            /** Format: int64 */
                            last_seen_ms?: number | null;
                            reference?: string | null;
                            severity: string;
                            source?: string | null;
                            tags?: string[] | null;
                            type: string;
                            value: string;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    market_signals: {
        parameters: {
            query: {
                key: string;
                from_ms: number;
                to_ms: number;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description market signal series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            key: string;
                            /** Format: int64 */
                            ts_ms: number;
                            /** Format: double */
                            value: number;
                        }[];
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
    get_extension_registry: {
        parameters: {
            query: {
                /** @description 固定页大小；当前协议只接受 64。 */
                limit: number;
                /** @description 前一签名页给出的不透明游标。 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 官方 Minisign 签名的扩展目录信封 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionRegistryEnvelope"];
                };
            };
            /** @description limit 或 cursor 无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 签名目录发布通道暂不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_ip_location: {
        parameters: {
            query?: {
                /** @description 访问者 IP (可选)。省略时按请求来源推断。 */
                ip?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description visitor city-level geolocation; zero coordinates on failure */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description 访问者 IP 地理定位结果 (供社区地图默认聚焦访问者所在城市)。
                         *     经纬度由服务端对访问者 IP 做地理定位得到; 定位失败时经纬度为 0。
                         */
                        data: {
                            city: string;
                            country: string;
                            /** Format: double */
                            latitude: number;
                            /** Format: double */
                            longitude: number;
                        };
                        meta: components["schemas"]["V2Meta"];
                    };
                };
            };
        };
    };
}
