fn main() {
    // 声明本应用全部自定义命令，让 tauri-build 生成 capabilities/*.json 引用的 ACL
    // permission。build.rs 是独立编译单元，看不到 lib.rs 的 generate_handler!，因此命令
    // 新增或改名时必须同步这里；遗漏会在 capability 校验阶段报 permission not found。
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            // agent 出站守卫 (两端通用); 其余为桌面内嵌浏览器命令。
            "agent_guarded_fetch",
            "open_browser_view",
            "browser_set_bounds",
            "browser_present",
            "browser_navigate",
            "browser_back",
            "browser_forward",
            "browser_reload",
            "browser_hide",
            "browser_show",
            "browser_close",
            "browser_get_backend",
            "browser_get_content",
            "browser_click",
            "browser_fill",
            "browser_press",
            "browser_list_interactive",
            "browser_wait",
            "browser_wait_for_selector",
            // ACP 外部智能体传输 (仅桌面注册, 但命令名须在此声明以生成 ACL permission)。
            "acp_spawn",
            "acp_send",
            "acp_close",
            // ACP 入站服务端 (暴露方向: 编辑器连入)。
            "acp_listen_start",
            "acp_listen_stop",
            "acp_server_send",
            "acp_server_close",
            // 外部智能体检测 (设置里点选即用) + 内置脚本定位 + 一次性运行 (暴露自测)。
            "acp_which",
            "acp_script_path",
            "acp_run_once",
            // 桌面 OAuth 环回回调监听；仅主窗口 capability 可启动或停止。
            "oauth_callback_start",
            "oauth_callback_stop",
            "runtime_extension_discover",
            "runtime_extension_verify",
            "runtime_extension_spawn",
            "runtime_extension_registry_snapshot",
            "runtime_extension_registry_refresh",
            "runtime_extension_update_prepare",
            "runtime_extension_update_apply",
            "runtime_extension_update_discard",
            "runtime_extension_publisher_rotation_inspect",
            "runtime_extension_publisher_rotation_apply",
            "list_installed_apps",
            "launch_installed_app",
            "read_app_icon_data_url",
            "guarded_fs_pick_root",
            "guarded_fs_grant_info",
            "guarded_fs_revoke_grant",
            "guarded_fs_stat",
            "guarded_fs_list",
            "guarded_fs_read",
            "guarded_fs_write_text",
            "secure_store_status",
            "secure_store_get",
            "secure_store_set",
            "secure_store_delete",
            "secure_store_self_test",
            "window_minimize",
            "window_close",
            "window_toggle_maximize",
            "window_query_maximized",
            "open_engine_window",
        ]),
    ))
    .expect("failed to run tauri-build")
}
