// design-sync bundle entry — re-exports exactly the core UI primitives (the
// shadcn-style components in src/ui that are NOT Plate editor internals).
// The converter bundles this into window.IdeallUI.*; `--entry .design-sync/entry.ts`.
// `@/…` aliases resolve via tsconfig.json paths (the converter's esbuild plugin).
export * from "@/ui/badge"
export * from "@/ui/button"
export * from "@/ui/calendar"
export * from "@/ui/card"
export * from "@/ui/checkbox"
export * from "@/ui/command"
export * from "@/ui/dialog"
export * from "@/ui/dropdown-menu"
export * from "@/ui/empty-state"
export * from "@/ui/hover-card"
export * from "@/ui/input"
export * from "@/ui/label"
export * from "@/ui/popover"
export * from "@/ui/select"
export * from "@/ui/separator"
export * from "@/ui/sheet"
export * from "@/ui/sonner"
export * from "@/ui/table"
export * from "@/ui/tabs"
export * from "@/ui/textarea"
export * from "@/ui/tooltip"
