/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/authorize/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /authorize/authorize — 校验 JWT 并回显当前用户 claims 数据。 */
        get: operations["authorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorize/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /authorize/login — 登录并签发 JWT。 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorize/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /authorize/register — 注册账号并签发 JWT。 */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorize/secret/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /authorize/secret/{client_id} — 下发服务端临时 X25519 公钥 (hex 明文串)。
         * @description 注意: 响应体是裸 hex 字符串, **不可** 包成 `Json<String>` —— 否则会被加上引号,
         *     破坏 myos 端按裸串解析的 wire 格式。
         */
        get: operations["get_server_public_key"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_info"];
        put?: never;
        post: operations["get_latest_info"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_related_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/entity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /info/entity?label=&name= — 实体详情聚合 (peer 实体页 / admin 钻取) */
        get: operations["get_entity_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/entity/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /info/entity/search?q=&limit= — 实体搜索 (按提及信息数倒序) */
        get: operations["search_entities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/entity/{hour}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_entity_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["get_info_events"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/geoip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /info/geoip?ip= — 定位访问者 IP 所在城市 (peer community 地图默认聚焦) */
        get: operations["get_ip_location"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /info/latest — 返回最新 200 条信息（admin 前端调用） */
        get: operations["get_latest_info_simple"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/publishers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_publishers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/publishers/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /info/publishers/locations — 发布者地理位置 (peer community 地图) */
        get: operations["get_publisher_locations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["query_info_by_params"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** PUT /me/profile — 更新自己的展示名 (需登录)。 */
        put: operations["update_profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /me/publications — 发布一条内容 (需登录)。 */
        post: operations["create_publication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/publications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** DELETE /me/publications/{id} — 删除自己的一条发布 (需登录)。 */
        delete: operations["delete_publication"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/peer/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /peer/{id} — 某发布者公开档案 (公开)。 */
        get: operations["get_publisher"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/peer/{id}/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /peer/{id}/publications — 某发布者的发布列表 (公开)。 */
        get: operations["list_publications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/peers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /peers — 社区发布者列表 (公开, 供 community 浏览订阅)。 */
        get: operations["list_publishers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /sync/{id} — 取回端到端加密的同步块 (服务端不可读内容)。 */
        get: operations["get_sync_blob"];
        /** PUT /sync/{id} — 覆盖式上传端到端加密的同步块。 */
        put: operations["put_sync_blob"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/has/email/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["has_email_exist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthBody: {
            token: string;
            token_type: string;
        };
        /**
         * @description 注册 / 登录请求体。密码经客户端公钥与服务端临时密钥协商出的共享密钥
         *     AEAD 加密后, 以 hex 字符串传输。
         */
        AuthPayload: {
            /** @description 用户(浏览器)指纹, 用作 SessionID */
            client_id: string;
            /** @description 客户端 X25519 公钥 (hex) */
            client_secret: string;
            email: string;
            /** @description 加密后的密码 (hex): 前 24 字节为 nonce, 末 16 字节为 Poly1305 标签, 中间为密文 */
            encrypted_password: string;
        };
        /**
         * @description 实体摘要 (实体搜索结果项 / 实体详情的共现实体项)。
         *     跨周聚合口径: 按 `(name, label)` 值合并全部 period 分桶节点 (见 NameEntity 的周分桶说明)。
         */
        EntityBrief: {
            /**
             * Format: int32
             * @description 提及该实体的信息条数 (共现项 = 与目标实体共同出现的信息条数)
             */
            count: number;
            /** @description 任一分桶节点有百科词条即为 true */
            has_entry: boolean;
            label: string;
            name: string;
        };
        /**
         * @description 实体详情聚合 (`GET /info/entity?label=&name=`): 跨周合并该 `(name, label)` 的全部分桶节点。
         *     实体不存在时返回 `mention_count = 0` 的空详情 (与 `/info` 系列「查无返回空默认」口径一致)。
         */
        EntityDetail: {
            baike_url?: string | null;
            /** @description 共现实体 top N (按共同出现的信息条数倒序) */
            co_entities: components["schemas"]["EntityBrief"][];
            /**
             * Format: int64
             * @description 最早/最晚提及的采集时间 (epoch 毫秒; 无提及时为 0)
             */
            first_seen: number;
            /** @description 是否有百科词条 (任一分桶节点为 true 即 true) */
            has_entry: boolean;
            label: string;
            /** Format: int64 */
            last_seen: number;
            /**
             * Format: int32
             * @description 提及该实体的信息总条数
             */
            mention_count: number;
            name: string;
            /** @description 按周 period 的提及分布 (升序), 供趋势展示 */
            weekly: components["schemas"]["EntityPeriodCount"][];
            wikipedia_url?: string | null;
        };
        /** @description 实体的单周提及量 (`period` = 周一零点 epoch 毫秒, 与 NameEntity.period 同口径)。 */
        EntityPeriodCount: {
            /** Format: int32 */
            count: number;
            /** Format: int64 */
            period: number;
        };
        /**
         * @description 近 N 小时各类实体频次 (`GET /info/entity/{hour}`), 每类 top 20 的 `{name: count}`。
         *     覆盖入图的全部五类 (TIME 实体不入图故无此类)。
         */
        EntityStats: {
            event: {
                [key: string]: number;
            };
            loc: {
                [key: string]: number;
            };
            org: {
                [key: string]: number;
            };
            per: {
                [key: string]: number;
            };
            product: {
                [key: string]: number;
            };
        };
        Info: {
            /** Format: int64 */
            collect_time: number;
            data: string;
            labels: components["schemas"]["NameEntity"][];
            language: string;
            /** Format: int64 */
            publish_time: number;
            publisher: components["schemas"]["Publisher"];
            title: string;
            url: string;
        };
        /** @description 同一事件的多来源报道聚类 (`POST /info/events`)。 */
        InfoEvent: {
            /** @description 代表稿: 聚类内最新采集的一篇 */
            lead: components["schemas"]["Info"];
            /** @description 同事件其它来源 (不含 lead, 按采集时间倒序) */
            related: components["schemas"]["Info"][];
            /**
             * Format: int32
             * @description 报道总数 (含 lead)
             */
            source_count: number;
        };
        /**
         * @description 访问者 IP 地理定位结果 (供 peer community 地图默认聚焦访问者所在城市)。
         *     经纬度由 super/server 对访问者 IP 做地理定位得到; 定位失败时经纬度为 0。
         */
        IpLocation: {
            city: string;
            country: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        /**
         * @description 命名实体 (NER 结果)。`label` 取值见 super/form 的 NER schema:
         *     `PER` / `ORG` / `LOC` / `TIME` / `PRODUCT` / `EVENT`。`period` 为所属周 (周一 0 点) 的 epoch 毫秒。
         *
         *     词条富化字段 (super/form 查百度百科 + 维基百科后写入): `has_entry` 标记该实体是否有百科词条,
         *     `baike_url` / `wikipedia_url` 为对应词条链接。`#[serde(default)]` 保证旧数据 (无这些字段) 反序列化安全。
         */
        NameEntity: {
            baike_url?: string | null;
            has_entry?: boolean;
            label: string;
            name: string;
            /** Format: int64 */
            period: number;
            wikipedia_url?: string | null;
        };
        /** @description 发布请求体 (POST /me/publications)。 */
        NewPublication: {
            body?: string;
            title: string;
            url?: string;
        };
        /** @description 社区发布者 (用户) 公开档案 + 发布数。`id` 即订阅键 (myos `type:"peer"` 的 key)。 */
        PeerPublisher: {
            /**
             * Format: int64
             * @description 用户节点 id (= JWT claims.id)
             */
            id: number;
            name: string;
            /** Format: int64 */
            publication_count: number;
        };
        /** @description 档案更新请求体 (PUT /me/profile)。MVP 仅改展示名。 */
        ProfileUpdate: {
            name: string;
        };
        /** @description 一条发布内容。 */
        Publication: {
            /** @description 正文/笔记 (可空) */
            body: string;
            /**
             * Format: int64
             * @description 发布时间 (epoch 毫秒)
             */
            created_at: number;
            /**
             * Format: int64
             * @description 发布物 (publication) id
             */
            id: number;
            title: string;
            /** @description 关联链接 (可空) */
            url: string;
        };
        Publisher: {
            domain: string;
            name: string;
            /** Format: int64 */
            period: number;
        };
        /**
         * @description 发布者地理位置 (供 peer community 地图展示)。
         *     经纬度由 super/server 对发布者域名做 IP 地理定位得到。
         */
        PublisherLocation: {
            city: string;
            /**
             * Format: int32
             * @description 该发布者的信息条数 (地图点大小依据)
             */
            count: number;
            country: string;
            domain: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            name: string;
        };
        QueryInfoParams: {
            /** @description 实体筛选, 每项为 `(label, name)` */
            entity_label_name?: [
                string,
                string
            ][] | null;
            /**
             * @description 分页 `(page_size, page_index)`；实际 skip = page_size * page_index。
             *     注意 `u8` 上限 255：单页最多 255 条、页码最多 255（当前数据量够用，未在 OpenAPI 契约暴露）。
             */
            page_size_offset?: [
                number,
                number
            ] | null;
            /** @description 限定发布者域名 */
            publisher_domain?: string | null;
            /** @description `[from, to]` 时间戳毫秒区间, 闭区间 (与存储一致: super/form 存 epoch 毫秒, 查询用 datetime.fromepochmillis) */
            timestamp_from_to?: [
                number,
                number
            ] | null;
        };
        /**
         * @description `GET /info/analysis` 响应项: Info + 关联强度分数。
         *     `#[serde(flatten)]` 让 JSON 形状 = Info 字段平铺 + 两个分数字段:
         *     旧消费方仍可按 Info 读 (向后兼容), 新消费方据分数解释「为什么相关」并展示共享强度。
         */
        RelatedInfo: components["schemas"]["Info"] & {
            /**
             * Format: int32
             * @description 与目标共享的实体数 (全实体口径, 兜底阈值 min_shared)
             */
            shared: number;
            /**
             * Format: int32
             * @description 与目标共享且两侧都有百科词条的实体数 (更可信, 低阈值 min_shared_entry 即连边)
             */
            shared_entry: number;
        };
        SyncBlob: {
            /** @description 密文 (base64); 明文为客户端订阅列表 JSON, 服务端不可读 */
            ciphertext: string;
            /** @description AES-GCM 初始向量 (base64) */
            iv: string;
            /**
             * Format: int64
             * @description 客户端写入时间戳 (毫秒), 由客户端提供
             */
            updated_at: number;
        };
        UserClaimsData: {
            avatar?: string | null;
            email: string;
            /** Format: int64 */
            id: number;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户 claims 数据 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserClaimsData"];
                };
            };
            /** @description 缺失或非法的 JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthPayload"];
            };
        };
        responses: {
            /** @description 登录成功, 返回 JWT */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthBody"];
                };
            };
            /** @description 密码或密钥 hex 格式非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 登录失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthPayload"];
            };
        };
        responses: {
            /** @description 注册成功, 返回 JWT */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthBody"];
                };
            };
            /** @description 密码或密钥 hex 格式非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 邮箱已被注册 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 创建失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_server_public_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 客户端(浏览器)指纹, 用作 SessionID */
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务端临时公钥 (hex 明文串) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description 获取密钥失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_info: {
        parameters: {
            query: {
                /** @description 信息 URL (主键) */
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description URL 对应的信息, 不存在时返回默认空 Info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Info"];
                };
            };
        };
    };
    get_latest_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryInfoParams"];
            };
        };
        responses: {
            /** @description 命中的信息列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Info"][];
                };
            };
        };
    };
    get_related_info: {
        parameters: {
            query: {
                /** @description 信息 URL (主键) */
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 与给定 URL 关联的信息列表 (Info 字段平铺 + shared/shared_entry 关联强度), 按相关度倒序, 至多 info.related.limit (默认 50) 条 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedInfo"][];
                };
            };
        };
    };
    get_entity_detail: {
        parameters: {
            query: {
                /** @description 实体类别 (PER / ORG / LOC / PRODUCT / EVENT) */
                label: string;
                /** @description 实体名 */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 实体详情 (提及量/首末时间/周分布/词条链接/共现实体); 实体不存在时 mention_count 为 0 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
        };
    };
    search_entities: {
        parameters: {
            query: {
                /** @description 实体名子串 (CONTAINS 匹配) */
                q: string;
                /** @description 返回条数上限 (默认 20) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 命中的实体摘要列表 (跨周分桶已按 (name,label) 聚合) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityBrief"][];
                };
            };
        };
    };
    get_entity_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 回溯小时数 */
                hour: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 近 N 小时五类实体频次 (每类 top 20 的 `{name: count}`) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityStats"];
                };
            };
        };
    };
    get_info_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryInfoParams"];
            };
        };
        responses: {
            /** @description 按同一事件聚类后的报道列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoEvent"][];
                };
            };
        };
    };
    get_ip_location: {
        parameters: {
            query: {
                /** @description 访问者 IP (由 peer 从 x-forwarded-for 提取后透传; 服务端不直接读 client IP, 因调用方为 myos) */
                ip: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description IP 地理定位结果; 定位失败 (非法/私网/网络) 时经纬度为 0 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpLocation"];
                };
            };
        };
    };
    get_latest_info_simple: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 最新 200 条信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Info"][];
                };
            };
        };
    };
    get_publishers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 发布者 `{domain: name}` 映射 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_publisher_locations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 有坐标的发布者位置列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublisherLocation"][];
                };
            };
        };
    };
    query_info_by_params: {
        parameters: {
            query?: {
                /** @description 发布站点域名筛选 (可选) */
                domain?: string;
                /** @description 起始时间戳 (毫秒, 可选) */
                start_time?: number;
                /** @description 结束时间戳 (毫秒, 可选) */
                end_time?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 命中的信息列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Info"][];
                };
            };
        };
    };
    update_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description 已更新 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 名称为空 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 更新失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_publication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPublication"];
            };
        };
        responses: {
            /** @description 已发布 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Publication"];
                };
            };
            /** @description 标题为空 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 发布失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_publication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 发布 id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 删除失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_publisher: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 发布者(用户) id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 发布者档案 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerPublisher"];
                };
            };
            /** @description 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_publications: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 发布者(用户) id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 发布列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Publication"][];
                };
            };
        };
    };
    list_publishers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 发布者列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerPublisher"][];
                };
            };
        };
    };
    get_sync_blob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 同步码派生的存储 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 加密同步块 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncBlob"];
                };
            };
            /** @description 该 id 尚无同步数据 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_sync_blob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 同步码派生的存储 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncBlob"];
            };
        };
        responses: {
            /** @description 已保存 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description id 非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 保存失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    has_email_exist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 待校验的邮箱 */
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 邮箱已存在 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 邮箱未注册 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
